[sym_params]
; Bit 0: to println in serial as debug 
; Bit 1: fc bridge for telemetry 
; Bit 2: cam enable 
; Bit 3: joystick control 
enable_debug = 1
enable_fc = 0
enable_cam = 1
enable_joy_control = 0

[vid_reso]
; 0: 96x96 (96X96)
; 1: 160x120 (QQVGA)
; 2: 128x128 (128X128)
; 3: 176x144 (QCIF)
; 4: 240x176 (HQVGA)
; 5: 240x240 (240X240)
; 6: 320x240 (QVGA)
; 7: 320x320 (320X320)
; 8: 400x296 (CIF)
; 9: 480x320 (HVGA)
; 10: 640x480 (VGA)
reso_i = 10

[mavlink_tele]
; Bit 0: HEARTBEAT (0)
; Bit 1: DISTANCE_SENSOR (132) 
; Bit 2: OPTICAL_FLOW_RAD (106) 
msg_heartbeat = 1
msg_distance_sensor = 1
msg_optical_flow_rad = 1